# RPCore ayarlari
baslangic-bakiye: 500.0

is:
  ciftci-odeme: 4.0        # ekin hasat basina
  madenci-odeme: 5.0       # cevher basina
  balikci-odeme: 6.0       # balik basina
  polis-maas: 50.0         # nobet basina (10 dakikada bir)
  polis-nobet-araligi-saniye: 600

susama:
  azalma-araligi-saniye: 60
  azalma-miktari: 2.0
  kritik-esik: 20.0

takim:
  kurma-ucreti: 1000.0
  katilma-ucreti: 100.0

araba:
  ekonomik-fiyat: 800.0
  spor-fiyat: 2500.0
  luks-fiyat: 5000.0
  gunluk-kira-carpani: 0.05
