name: Build RpCore

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Kodu çek
        uses: actions/checkout@v4

      - name: JDK 25 kur
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '25'
          cache: 'maven'

      - name: Maven ile derle
        run: mvn -B clean package

      - name: Jar dosyasını yükle (artifact)
        uses: actions/upload-artifact@v4
        with:
          name: SkriptVeri
          path: target/RPCore-*.jar
